dtb-$(CONFIG_ARCH_P660)		+= hip05-d02.dtb hip05-2p1s.dtb hip05-lemon.dtb hip05-s01.dtb hip05-2p2s.dtb
dtb-$(CONFIG_ARCH_Hi1610)	+= hisi_hi1612_1p.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
