dtb-$(CONFIG_ARCH_P660)		+= hisi_p660_evb.dtb hisi_p660_evb_pangea.dtb hip05-d02.dtb hip05-2p1s.dtb hip05-lemon.dtb hip05-s01.dtb hip05-2p2s.dtb
dtb-$(CONFIG_ARCH_Hi1610)	+= hi1610_16c-evb.dtb hi1610_32c-evb.dtb hisi_hi1610_2p.dtb hi1610_pangea.dtb hisi_hi1612_1p.dtb
dtb-$(CONFIG_ARCH_Hi1616)       += hi1616_1p.dtb hi1616_2p.dtb hi1616_4p.dtb hi1616_1p_evb.dtb hi1616_2p_evb.dtb hi1616_4p_evb.dtb hi1616_2p_ec.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
